CoordinateMappingManager Class Reference
The CoordinateMappingManager class is a class that is responsible for converting coordinates values from a coordinates' space to another one. A certain coordinates' space has to inherit from this class and implement its own conversion method, overriding the base class method.
#include <CoordinateMappingManager.hpp>
Public Member Functions
CoordinateMappingManager (Room room)
Construct a new Coordinate Mapping Manager object.
virtual std::vector< Point3D * > * mapToMeters (std::vector< Point3D * > pointsToMap, std::vector< bool > bodyKeyPointsMap, float xOrigin, float zOrigin)
This method requires pointers' Point3D's vector, the related vector map, and the original coordinates' space origins. It returns a pointer to pointers' Point3D's vector that actually contains all input Points whose coordinates' values have been converted to the new coordinates' space. In the parent class, the conversion just converts the RealSense's values to more accessible axes' origins.
Protected Member Functions
Room getRoom (void)
Returns the room object.
float transformWidthCoordinate (float widthCoordinate)
Converts width value.
float transformHeightCoordinate (float heightCoordinate)
Converts height value.
float inverseTransform (float inputNumber)
Implements the inverse conversion on the input value.
Protected Attributes
const Room room
Specific room within which the coordinate mapping will be done.
Detailed Description
The CoordinateMappingManager class is a class that is responsible for converting coordinates values from a coordinates' space to another one. A certain coordinates' space has to inherit from this class and implement its own conversion method, overriding the base class method.
See also
 https://math.stackexchange.com/questions/685110/how-to-determine-coordinates-on-two-different-size-rectangles
Definition at line 28 of file CoordinateMappingManager.hpp.
Constructor & Destructor Documentation
CoordinateMappingManager()
CoordinateMappingManager::CoordinateMappingManager (Room room) [inline]
Construct a new Coordinate Mapping Manager object.
Parameters
room Specific room within which the coordinate mapping will be done.
Definition at line 63 of file CoordinateMappingManager.hpp.
: room(room) { }
Member Function Documentation
getRoom()
Room CoordinateMappingManager::getRoom (void) [protected]
Returns the room object.
Returns
Room
Definition at line 16 of file CoordinateMappingManager.cpp.
                                            {
    return this->room;
}
References room.
Referenced by mapToMeters(), UnityCoordinateMappingManager::mapToMeters(), transformHeightCoordinate(), and transformWidthCoordinate().
inverseTransform()
float CoordinateMappingManager::inverseTransform (float inputNumber) [protected]
Implements the inverse conversion on the input value.
Parameters
inputNumber Input value to convert.
Returns
float
Definition at line 42 of file CoordinateMappingManager.cpp.
                                                                   {
    float outputNumber = 0.0;
    if (inputNumber >= 1) {
        outputNumber = (1 - 2 * inputNumber);
    } else if (inputNumber <= -1) {
        outputNumber = (-(1 + 2 * inputNumber));
    } else {
        outputNumber = (1 - std::abs(inputNumber) + 0.25);
    }
    
    return outputNumber;
}
mapToMeters()
std::vector< Point3D * > * CoordinateMappingManager::mapToMeters (std::vector< Point3D * > pointsToMap, std::vector< bool > bodyKeyPointsMap, float xOrigin, float zOrigin) [virtual]
This method requires pointers' Point3D's vector, the related vector map, and the original coordinates' space origins. It returns a pointer to pointers' Point3D's vector that actually contains all input Points whose coordinates' values have been converted to the new coordinates' space. In the parent class, the conversion just converts the RealSense's values to more accessible axes' origins.
Parameters
pointsToMap
bodyKeyPointsMap
xOrigin
zOrigin
Returns
std::vector <Point3D *> *
Reimplemented in UnityCoordinateMappingManager.
Definition at line 57 of file CoordinateMappingManager.cpp.
                                                                                                                                                                 {
    std::vector <Point3D *> * newPoints = new std::vector <Point3D *>;
    
    for (unsigned char i = 0; i < bodyKeyPointsMap.size(); i++) {
        if (!bodyKeyPointsMap.at(i)) {
            newPoints->push_back(new Point3D(0, 0, 0, new BodyKeyPoint(0, 0, 0)));
        } else {
            newPoints->push_back(new Point3D(
                transformWidthCoordinate(pointsToMap.at(i)->getX()),
                transformHeightCoordinate(pointsToMap.at(i)->getY()),
                pointsToMap.at(i)->getZ() - zOrigin + getRoom().getDistanceCameraFromBackWall(),
                new BodyKeyPoint(0, 0, ((BodyKeyPoint *) pointsToMap.at(i)->getDecorated())->getConfidence()))
            );
        }
    }
    
    return newPoints;
}
References getRoom(), transformHeightCoordinate(), and transformWidthCoordinate().
Referenced by Skeleton::generateSkeleton().
transformHeightCoordinate()
float CoordinateMappingManager::transformHeightCoordinate (float heightCoordinate) [protected]
Converts height value.
Parameters
heightCoordinate Input height value.
Returns
float
Definition at line 26 of file CoordinateMappingManager.cpp.
                                                                                 {
// float environmentHeight = std::abs(getRoom().getMinHeight()) + std::abs(getRoom().getMaxHeight());
// float environmentHeightRS = std::abs(getRoom().getMinHeightRS()) + std::abs(getRoom().getMaxHeightRS());
// float tempHeight = -(((heightCoordinate - getRoom().getMaxHeightRS()) / environmentHeightRS) * environmentHeight) + getRoom().getMinHeight();
// return std::abs(tempHeight) - 0.9;
    
    float newHeightCoordinate = -heightCoordinate + getRoom().getMaxHeightRS() - getRoom().getHeightOffset();
    if (newHeightCoordinate >= getRoom().getMaxHeight()) {
        return getRoom().getMaxHeight();
    } else if (newHeightCoordinate <= 0) {
        return 0;
    }
    return newHeightCoordinate;
}
References Room::getHeightOffset(), Room::getMaxHeight(), Room::getMaxHeightRS(), and getRoom().
Referenced by mapToMeters(), and UnityCoordinateMappingManager::mapToMeters().
transformWidthCoordinate()
float CoordinateMappingManager::transformWidthCoordinate (float widthCoordinate) [protected]
Converts width value.
Parameters
widthCoordinate Input width value.
Returns
float
Definition at line 20 of file CoordinateMappingManager.cpp.
                                                                               {
    float environmentWidth = std::abs(getRoom().getMinWidth()) + std::abs(getRoom().getMaxWidth());
    float environmentWidthRS = std::abs(getRoom().getMinWidthRS()) + std::abs(getRoom().getMaxWidthRS());
    return (((widthCoordinate - getRoom().getMinWidthRS()) / environmentWidthRS) * environmentWidth) + getRoom().getMinWidth();
}
References Room::getMinWidth(), and getRoom().
Referenced by mapToMeters(), and UnityCoordinateMappingManager::mapToMeters().
Member Data Documentation
room
const Room CoordinateMappingManager::room [protected]
Specific room within which the coordinate mapping will be done.
Definition at line 33 of file CoordinateMappingManager.hpp.
Referenced by getRoom().
The documentation for this class was generated from the following files:
Managers/CoordinateManagers/CoordinateMappingManager.hpp
Managers/CoordinateManagers/CoordinateMappingManager.cpp