OpenPoseCommand Class Reference
The OpenPoseCommand class is a class that implements a command to start and run OpenPose.
#include <SystemCommand.hpp>
Public Member Functions
void executeCommand (int *argc, char ***argv)
This method is responsible for executing commands on the system based on the filled command string. If the string is empty, then no command is executed.
Protected Member Functions
void setCommand (int *argc, char ***argv) override
Set the string command to an OpenPose properly formatted command.
void setCommand (std::string command)
Set the string command with a particularly given string passed as a parameter.
std::string getCommand (void)
Get the string command.
Private Attributes
std::string command
The final command given to the system by the program.
Detailed Description
The OpenPoseCommand class is a class that implements a command to start and run OpenPose.
Definition at line 88 of file SystemCommand.hpp.
Member Function Documentation
executeCommand()
void SystemCommand::executeCommand (int * argc, char *** argv) [inherited]
This method is responsible for executing commands on the system based on the filled command string. If the string is empty, then no command is executed.
Parameters
argc pointer to argc from the main function or based on what the program reads from the configuration file.
argv pointer to argv from the main function or based on what the program reads from the configuration file.
Definition at line 23 of file SystemCommand.cpp.
                                                             {
    setCommand(argc, argv);
    if (getCommand().size() > 0 && getCommand() != "OP") std::system(getCommand().c_str());
}
References SystemCommand::getCommand(), and SystemCommand::setCommand().
Referenced by FacadeSingleton::cleanBuildFolder(), and FacadeSingleton::getVideoBodyKeyPoints().
getCommand()
std::string SystemCommand::getCommand (void) [protected], [inherited]
Get the string command.
Returns
std::string
Definition at line 19 of file SystemCommand.cpp.
                                         {
    return this->command;
}
References SystemCommand::command.
Referenced by SystemCommand::executeCommand().
setCommand() [1/2]
void OpenPoseCommand::setCommand (int * argc, char *** argv) [override], [protected], [virtual]
Set the string command to an OpenPose properly formatted command.
Parameters
argc pointer to argc from the main function.
argv pointer to argv from the main function.
Implements SystemCommand.
Definition at line 130 of file OpenPoseCommand.cpp.
                                                           {
    UsageManager * usageManagerInstance = UsageManager::getInstance();
    if (usageManagerInstance == nullptr) CV_Error(USAGE_MANAGER_NULLPTR_ERROR, USAGE_MANAGER_NULLPTR_SCOPE);
    char *** localArgv = usageManagerInstance->get_argv();
    std::stringstream openPoseTerminalCommand;
    const char * openPoseFolder = (* localArgv)[openPoseFolderOffset];
    const char * openPoseExecuteCommand = (* localArgv)[openPoseExecuteCommandOffset];
    const char * imagesFolder = (* localArgv)[imagesFolderOffset];
    const char * outputFolder = (* localArgv)[outputFolderOffset];
    
    openPoseTerminalCommand << "cd " << openPoseFolder << " && " << openPoseExecuteCommand
                            << " --net_resolution -1x128 --num_gpu 1 --num_gpu_start 2 --display 0 --render_pose 0 --image_dir "
                            << imagesFolder << "rgb/" << " --write_json " << outputFolder << "op/"
                            << " --logging_level 255 > /dev/null";
    SystemCommand::setCommand(std::string(openPoseTerminalCommand.str()));
}
References UsageManager::get_argv(), UsageManager::getInstance(), imagesFolderOffset, openPoseExecuteCommandOffset, openPoseFolderOffset, outputFolderOffset, SystemCommand::setCommand(), USAGE_MANAGER_NULLPTR_ERROR, and USAGE_MANAGER_NULLPTR_SCOPE.
setCommand() [2/2]
void SystemCommand::setCommand (std::string command) [protected], [inherited]
Set the string command with a particularly given string passed as a parameter.
Parameters
command
Definition at line 15 of file SystemCommand.cpp.
                                                 {
    this->command = command;
}
References SystemCommand::command.
Member Data Documentation
command
std::string SystemCommand::command [private], [inherited]
The final command given to the system by the program.
Definition at line 33 of file SystemCommand.hpp.
Referenced by SystemCommand::getCommand(), and SystemCommand::setCommand().
The documentation for this class was generated from the following files:
Command/SystemCommand.hpp
Command/OpenPoseCommand.cpp