Point3D Class Reference
Point3D class is used for Point3D creations and manipulations.
#include <Point3D.hpp>
Public Member Functions
Point3D (float x, float y, float z, Point *decorated=nullptr)
Construct a new Point 3D object.
float getZ (void)
Get the Point's z coordinate value.
float getX (void)
Get the Point's x coordinate value.
float getY (void)
Get the Point's y coordinate value.
const Point * getDecorated (void)
Get the pointer to Point used to check if that's a `decorated` Point.
Protected Member Functions
void setX (float x)
Set the Point's x coordinate value.
void setY (float y)
Set the Point's y coordinate value.
Private Member Functions
void setZ (float z)
Set the Point's z coordinate value.
Private Attributes
float z
Point's z coordinate.
float x
Point's x coordinate.
float y
Point's y coordinate.
const Point * decorated
A pointer to Point.
Detailed Description
Point3D class is used for Point3D creations and manipulations.
Point3D class is a class that represents a Point with its own x coordinate, y coordinate, and z coordinate. This class inherits from Point and adds the `z coordinate` detail.
Definition at line 23 of file Point3D.hpp.
Constructor & Destructor Documentation
Point3D()
Point3D::Point3D (float x, float y, float z, Point * decorated = nullptr)
Construct a new Point 3D object.
Parameters
x Point's x coordinate value.
y Point's y coordinate value.
z Point's z coordinate value.
decorated
See also
Point (float x, float y, Point * decorated = nullptr) : decorated(decorated)
Definition at line 21 of file Point3D.cpp.
                                                              : Point(x, y, decorated) {
    setZ(z);
}
References setZ(), and z.
Member Function Documentation
getDecorated()
const Point * Point::getDecorated (void) [inherited]
Get the pointer to Point used to check if that's a `decorated` Point.
Returns
const Point *
Definition at line 37 of file Point.cpp.
                                       {
    return this->decorated;
}
References Point::decorated.
Referenced by Point::~Point().
getX()
float Point::getX (void) [inherited]
Get the Point's x coordinate value.
Returns
float
Definition at line 29 of file Point.cpp.
                       {
    return this->x;
}
References Point::x.
getY()
float Point::getY (void) [inherited]
Get the Point's y coordinate value.
Returns
float
Definition at line 33 of file Point.cpp.
                       {
    return this->y;
}
References Point::y.
getZ()
float Point3D::getZ (void)
Get the Point's z coordinate value.
Returns
float
Definition at line 25 of file Point3D.cpp.
                         {
    return this->z;
}
References z.
setX()
void Point::setX (float x) [protected], [inherited]
Set the Point's x coordinate value.
Parameters
x Point's x coordinate value.
Definition at line 15 of file Point.cpp.
                         {
    this->x = x;
}
References Point::x.
Referenced by Point::Point().
setY()
void Point::setY (float y) [protected], [inherited]
Set the Point's y coordinate value.
Parameters
y Point's y coordinate value.
Definition at line 19 of file Point.cpp.
                         {
    this->y = y;
}
References Point::y.
Referenced by Point::Point().
setZ()
void Point3D::setZ (float z) [private]
Set the Point's z coordinate value.
Parameters
z Point's z coordinate value.
Definition at line 15 of file Point3D.cpp.
                           {
    this->z = z;
}
References z.
Referenced by Point3D().
Member Data Documentation
decorated
const Point* Point::decorated [private], [inherited]
A pointer to Point.
Definition at line 34 of file Point.hpp.
Referenced by Point::getDecorated().
x
float Point::x [private], [inherited]
Point's x coordinate.
Definition at line 26 of file Point.hpp.
Referenced by Point::getX(), Point::Point(), and Point::setX().
y
float Point::y [private], [inherited]
Point's y coordinate.
Definition at line 30 of file Point.hpp.
Referenced by Point::getY(), Point::Point(), and Point::setY().
z
float Point3D::z [private]
Point's z coordinate.
Definition at line 28 of file Point3D.hpp.
Referenced by getZ(), Point3D(), and setZ().
The documentation for this class was generated from the following files:
Points/Point3D.hpp
Points/Point3D.cpp