UnityCoordinateMappingManager Class Reference
The UnityCoordinateMappingManager class is a class that is responsible for converting coordinates values from a coordinates' space to Unity coordinates' space whose parameters are specified at the top of this header file.
#include <CoordinateMappingManager.hpp>
Public Member Functions
UnityCoordinateMappingManager (Room room)
Construct a new Unity Coordinate Mapping Manager object.
std::vector< Point3D * > * mapToMeters (std::vector< Point3D * > pointsToMap, std::vector< bool > bodyKeyPointsMap, float xOrigin, float zOrigin) override
This method requires pointers' Point3D's vector, the related vector map, and the original coordinates' space origins. It returns a pointer to pointers' Point3D's vector that actually contains all input Points whose coordinates' values have been converted to the new coordinates' space. In this case, the method converts the values to Unity coordinates' space values whose configuration parameters are specified at the top of this header file.
Protected Member Functions
Room getRoom (void)
Returns the room object.
float transformWidthCoordinate (float widthCoordinate)
Converts width value.
float transformHeightCoordinate (float heightCoordinate)
Converts height value.
float inverseTransform (float inputNumber)
Implements the inverse conversion on the input value.
Protected Attributes
const Room room
Specific room within which the coordinate mapping will be done.
Detailed Description
The UnityCoordinateMappingManager class is a class that is responsible for converting coordinates values from a coordinates' space to Unity coordinates' space whose parameters are specified at the top of this header file.
See also
 https://math.stackexchange.com/questions/685110/how-to-determine-coordinates-on-two-different-size-rectangles
Definition at line 86 of file CoordinateMappingManager.hpp.
Constructor & Destructor Documentation
UnityCoordinateMappingManager()
UnityCoordinateMappingManager::UnityCoordinateMappingManager (Room room)
Construct a new Unity Coordinate Mapping Manager object.
Parameters
room Specific room within which the Unity' coordinate mapping will be done.
Definition at line 15 of file UnityCoordinateMappingManager.cpp.
: CoordinateMappingManager(room) { }
Member Function Documentation
getRoom()
Room CoordinateMappingManager::getRoom (void) [protected], [inherited]
Returns the room object.
Returns
Room
Definition at line 16 of file CoordinateMappingManager.cpp.
                                            {
    return this->room;
}
References CoordinateMappingManager::room.
Referenced by CoordinateMappingManager::mapToMeters(), mapToMeters(), CoordinateMappingManager::transformHeightCoordinate(), and CoordinateMappingManager::transformWidthCoordinate().
inverseTransform()
float CoordinateMappingManager::inverseTransform (float inputNumber) [protected], [inherited]
Implements the inverse conversion on the input value.
Parameters
inputNumber Input value to convert.
Returns
float
Definition at line 42 of file CoordinateMappingManager.cpp.
                                                                   {
    float outputNumber = 0.0;
    if (inputNumber >= 1) {
        outputNumber = (1 - 2 * inputNumber);
    } else if (inputNumber <= -1) {
        outputNumber = (-(1 + 2 * inputNumber));
    } else {
        outputNumber = (1 - std::abs(inputNumber) + 0.25);
    }
    
    return outputNumber;
}
mapToMeters()
std::vector< Point3D * > * UnityCoordinateMappingManager::mapToMeters (std::vector< Point3D * > pointsToMap, std::vector< bool > bodyKeyPointsMap, float xOrigin, float zOrigin) [override], [virtual]
This method requires pointers' Point3D's vector, the related vector map, and the original coordinates' space origins. It returns a pointer to pointers' Point3D's vector that actually contains all input Points whose coordinates' values have been converted to the new coordinates' space. In this case, the method converts the values to Unity coordinates' space values whose configuration parameters are specified at the top of this header file.
Parameters
pointsToMap
bodyKeyPointsMap
xOrigin
zOrigin
Returns
std::vector <Point3D *> *
Reimplemented from CoordinateMappingManager.
Definition at line 17 of file UnityCoordinateMappingManager.cpp.
                                                                                                                                                                      {
    std::vector <Point3D *> * newPoints = new std::vector <Point3D *>;
    for (unsigned char i = 0; i < bodyKeyPointsMap.size(); i++) {
        if (!bodyKeyPointsMap.at(i)) {
            newPoints->push_back(new Point3D(0, 0, 0, new BodyKeyPoint(0, 0, 0)));
        } else {
            newPoints->push_back(new Point3D(
                transformWidthCoordinate(pointsToMap.at(i)->getX()) - std::abs(xOrigin),
                transformHeightCoordinate(pointsToMap.at(i)->getY()),
                - (pointsToMap.at(i)->getZ() - zOrigin + getRoom().getDistanceCameraFromBackWall()),
                new BodyKeyPoint(0, 0, ((BodyKeyPoint *) pointsToMap.at(i)->getDecorated())->getConfidence()))
            );
        }
    }
    return newPoints;
}
References CoordinateMappingManager::getRoom(), CoordinateMappingManager::transformHeightCoordinate(), and CoordinateMappingManager::transformWidthCoordinate().
transformHeightCoordinate()
float CoordinateMappingManager::transformHeightCoordinate (float heightCoordinate) [protected], [inherited]
Converts height value.
Parameters
heightCoordinate Input height value.
Returns
float
Definition at line 26 of file CoordinateMappingManager.cpp.
                                                                                 {
// float environmentHeight = std::abs(getRoom().getMinHeight()) + std::abs(getRoom().getMaxHeight());
// float environmentHeightRS = std::abs(getRoom().getMinHeightRS()) + std::abs(getRoom().getMaxHeightRS());
// float tempHeight = -(((heightCoordinate - getRoom().getMaxHeightRS()) / environmentHeightRS) * environmentHeight) + getRoom().getMinHeight();
// return std::abs(tempHeight) - 0.9;
    
    float newHeightCoordinate = -heightCoordinate + getRoom().getMaxHeightRS() - getRoom().getHeightOffset();
    if (newHeightCoordinate >= getRoom().getMaxHeight()) {
        return getRoom().getMaxHeight();
    } else if (newHeightCoordinate <= 0) {
        return 0;
    }
    return newHeightCoordinate;
}
References Room::getHeightOffset(), Room::getMaxHeight(), Room::getMaxHeightRS(), and CoordinateMappingManager::getRoom().
Referenced by CoordinateMappingManager::mapToMeters(), and mapToMeters().
transformWidthCoordinate()
float CoordinateMappingManager::transformWidthCoordinate (float widthCoordinate) [protected], [inherited]
Converts width value.
Parameters
widthCoordinate Input width value.
Returns
float
Definition at line 20 of file CoordinateMappingManager.cpp.
                                                                               {
    float environmentWidth = std::abs(getRoom().getMinWidth()) + std::abs(getRoom().getMaxWidth());
    float environmentWidthRS = std::abs(getRoom().getMinWidthRS()) + std::abs(getRoom().getMaxWidthRS());
    return (((widthCoordinate - getRoom().getMinWidthRS()) / environmentWidthRS) * environmentWidth) + getRoom().getMinWidth();
}
References Room::getMinWidth(), and CoordinateMappingManager::getRoom().
Referenced by CoordinateMappingManager::mapToMeters(), and mapToMeters().
Member Data Documentation
room
const Room CoordinateMappingManager::room [protected], [inherited]
Specific room within which the coordinate mapping will be done.
Definition at line 33 of file CoordinateMappingManager.hpp.
Referenced by CoordinateMappingManager::getRoom().
The documentation for this class was generated from the following files:
Managers/CoordinateManagers/CoordinateMappingManager.hpp
Managers/CoordinateManagers/UnityCoordinateMappingManager.cpp