FacadeSingleton Class Reference
FacadeSingleton class is used as a single access point to a simplified interface.
#include <FacadeSingleton.hpp>
Public Member Functions
FacadeSingleton (FacadeSingleton &other)=delete
Disabling the possibility to clone the Singleton object. Singletons should not be cloneable.
void operator= (const FacadeSingleton &)=delete
Disabling the possibility to assign a Singleton object. Singletons should not be assignable.
RealSenseManager * getCameraManager (void)
Get the RealSenseManager pointer.
OutputManager * getOutputManager (void)
Get the OutputManager pointer.
OpenCV_Manager * getOpenCV_Manager (void)
Get the OpenCV_Manager pointer.
UsageManager * getUsageManager (void)
Get the UsageManager pointer.
CoordinateMappingManager * getCoordinateMappingManager (void)
Get the CoordinateMappingManager pointer.
ImageManager * getImageManager (void)
Get the ImageManager pointer.
KafkaManager * getKafkaManager (void)
Get the KafkaManager pointer.
void startEnvironment (rs2::pipeline &pipelineStream, struct rs2_intrinsics &color_intrin, float *scale, unsigned short int resX, unsigned short int resY, const char *destinationKafkaTopic, Room room)
This method is useful to invoke at the boot of the program where we want to initialize the different mangers, start the camera and set up the related environment.
void getVideoFrames (unsigned int user_nFrame, rs2::pipeline &pipelineStream, float scale, const unsigned short int framesToSkip)
Get user_nFrame video frames from the pipeline by applying a specific scaling factor.
void getVideoBodyKeyPoints (int *argc, char ***argv)
Start and execute OpenPose submodule.
void showSkeletons (unsigned int user_nFrame, const float skeletonThreshold)
Retrieve OpenPose's output, convert it to RealSense coordinate's space, show results and save them.
void sendData (unsigned int user_nFrame)
Send saved results by getVideoBodyKeyPoints(...) via Kafka using the KafkaManager.
void cleanBuildFolder (void)
This method cleans the build folder, in order to prepare the environment for the next loop iteration. It does this by deleting all images and JSON files produced during the current loop iteration.
Static Public Member Functions
static FacadeSingleton * getInstance (const int expected_argc, const char *expectedUsageMessage)
Get the unique class instance, given input parameters. This method should be called the first time when we want to create a reference to the object of this class.
static FacadeSingleton * getInstance (void)
Get the unique class instance. This methods should be called in the following scenario: when we just want to retrieve the reference to the object of this class.
Protected Member Functions
void setCameraManager (RealSenseManager *cameraManager)
Set the RealSenseManager pointer.
void setOutputManager (OutputManager *outputManager)
Set the OutputManager pointer.
void setOpenCV_Manager (OpenCV_Manager *openCV_Manager)
Set the OpenCV_Manager pointer.
void setUsageManager (UsageManager *usageManager)
Set the UsageManager pointer.
void setCoordinateMappingManager (CoordinateMappingManager *coordinateMappingManager)
Set the CoordinateMappingManager pointer.
void setImageManager (ImageManager *imageManager)
Set the ImageManager pointer.
void setKafkaManager (KafkaManager *kafkaManager)
Set the KafkaManager pointer.
Private Member Functions
FacadeSingleton (const int expected_argc=0, const char *expectedUsageMessage=nullptr)
Construct a new Facade Singleton object.
~FacadeSingleton (void)
Destroy the Facade Singleton object.
Private Attributes
RealSenseManager * cameraManager
A pointer to RealSenseManager object. A RealSenseManager object is responsible for handling the camera setup, frames acquisition and frames post-processing.
OutputManager * outputManager
A pointer to OutputManager object. An OutputManager object is responsible for handling the final output generation to send via Kafka later on.
OpenCV_Manager * openCV_Manager
A pointer to OpenCV_Manager object. An OpenCV_Manager object is responsible for converting camera frame to an OpenCV matrix and booting building skeletons into the image.
UsageManager * usageManager
A pointer to UsageManager object. An UsageManager object is responsible for checking if the parameters read from configuration file are fine, correct and valid. Furthermore this class provides methods to access this parameters.
CoordinateMappingManager * coordinateMappingManager
A pointer to CoordinateMappingManager object. A CoordinateMappingManager object is responsible for transforming one coordinate range values' space into another one. For instance, it can transform a RealSense coordinates space to meters or to Unity coordinates. In both cases, there are several parameters to set up regarding the scene and the room where the camera is installed.
ImageManager * imageManager
A pointer to CoordinateMappingManager object. A CoordinateMappingManager object is responsible for broad tasks such as loading, saving, and showing images, as well as releasing the memory allocated for those images.
KafkaManager * kafkaManager
A pointer to KafkaManager object. A KafkaManager object is responsible for sending previously produced JSON output via Kafka.
Static Private Attributes
static FacadeSingleton * sharedInstance { nullptr }
The field for storing the singleton instance.
static std::mutex singletonMutex
Mutex for thread-safe access.
Detailed Description
FacadeSingleton class is used as a single access point to a simplified interface.
A facade is a structural design pattern that provides a simplified interface to a library, a framework, or any other complex set of classes. A Facade class can often be transformed into a Singleton since a single facade object is sufficient in most cases. Since we need just one access point to this class and since the internal submodules are complex, a class FacadeSingleton implements both behaviors.
Definition at line 44 of file FacadeSingleton.hpp.
Constructor & Destructor Documentation
FacadeSingleton() [1/2]
FacadeSingleton::FacadeSingleton (const int expected_argc = 0, const char * expectedUsageMessage = nullptr) [private]
Construct a new Facade Singleton object.
Parameters
expected_argc the number of parameters that the program expects to find in the configuration file.
expectedUsageMessage a simple message that lets the user understand how to properly run the executable.
Definition at line 20 of file FacadeSingleton.cpp.
                                                                                            {
    std::ifstream inputFile(CONF_FILE_PATH);
    std::string singleLineConfigurationFile;
    
    int * fileArgc = new (std::nothrow) int;
    * fileArgc = (int) totalFileParameters;
    char *** fileArgv = new (std::nothrow) char **;
    * fileArgv = new (std::nothrow) char *[totalFileParameters];
    unsigned char rowCounter = 0;
    if (!fileArgc || !fileArgv || ! * fileArgv) CV_Error(NEW_ALLOC_ERROR, NEW_ALLOC_SCOPE);
    // Read usage's configuration parameters from file
    while (inputFile >> singleLineConfigurationFile) {
        (* fileArgv)[rowCounter] = new (std::nothrow) char [(unsigned int) singleLineConfigurationFile.size()];
        if (!(* fileArgv)[rowCounter]) CV_Error(NEW_ALLOC_ERROR, NEW_ALLOC_SCOPE);
        strcpy((* fileArgv)[rowCounter], singleLineConfigurationFile.c_str());
        rowCounter++;
    }
    
    setUsageManager(UsageManager::getInstance(fileArgc, fileArgv, expected_argc, expectedUsageMessage));
}
References CONF_FILE_PATH, expected_argc, expectedUsageMessage, UsageManager::getInstance(), NEW_ALLOC_ERROR, NEW_ALLOC_SCOPE, setUsageManager(), and totalFileParameters.
Referenced by getInstance().
 FacadeSingleton()
FacadeSingleton::~FacadeSingleton (void) [private]
Destroy the Facade Singleton object.
Definition at line 42 of file FacadeSingleton.cpp.
                                       {
    delete getCameraManager();
    delete getOutputManager();
    delete getOpenCV_Manager();
    delete getUsageManager();
    delete getCoordinateMappingManager();
    delete getImageManager();
    delete getKafkaManager();
    delete sharedInstance;
}
References getCameraManager(), getCoordinateMappingManager(), getImageManager(), getKafkaManager(), getOpenCV_Manager(), getOutputManager(), getUsageManager(), and sharedInstance.
FacadeSingleton() [2/2]
FacadeSingleton::FacadeSingleton (FacadeSingleton & other) [delete]
Disabling the possibility to clone the Singleton object. Singletons should not be cloneable.
Parameters
other
Member Function Documentation
cleanBuildFolder()
void FacadeSingleton::cleanBuildFolder (void)
This method cleans the build folder, in order to prepare the environment for the next loop iteration. It does this by deleting all images and JSON files produced during the current loop iteration.
Definition at line 166 of file FacadeSingleton.cpp.
                                            {
    SystemCommand * cleanCommand = new CleanCommand();
    cleanCommand->executeCommand(getUsageManager()->get_argc(), getUsageManager()->get_argv());
    delete cleanCommand;
}
References SystemCommand::executeCommand(), and getUsageManager().
Referenced by main(), and startEnvironment().
getCameraManager()
RealSenseManager * FacadeSingleton::getCameraManager (void)
Get the RealSenseManager pointer.
Returns
RealSenseManager *
See also
RealSenseManager.hpp
Definition at line 95 of file FacadeSingleton.cpp.
                                                          {
    return this->cameraManager;
}
References cameraManager.
Referenced by Skeleton::deprojectSkeletonPoints3D(), OpenCV_Manager::getVideoFramesCV(), sendData(), OpenCV_Manager::showSkeletonsCV(), startEnvironment(), and ~FacadeSingleton().
getCoordinateMappingManager()
CoordinateMappingManager * FacadeSingleton::getCoordinateMappingManager (void)
Get the CoordinateMappingManager pointer.
Returns
CoordinateMappingManager *
See also
constants.hpp
CoordinateMappingManager.hpp
Definition at line 111 of file FacadeSingleton.cpp.
                                                                             {
    return this->coordinateMappingManager;
}
References coordinateMappingManager.
Referenced by Skeleton::generateSkeleton(), and ~FacadeSingleton().
getImageManager()
ImageManager * FacadeSingleton::getImageManager (void)
Get the ImageManager pointer.
Returns
ImageManager *
See also
ImageManager.hpp
Definition at line 115 of file FacadeSingleton.cpp.
                                                     {
    return this->imageManager;
}
References imageManager.
Referenced by OpenCV_Manager::getVideoFramesCV(), OpenCV_Manager::showSkeletonsCV(), and ~FacadeSingleton().
getInstance() [1/2]
FacadeSingleton * FacadeSingleton::getInstance (const int expected_argc, const char * expectedUsageMessage) [static]
Get the unique class instance, given input parameters. This method should be called the first time when we want to create a reference to the object of this class.
Parameters
expected_argc the number of parameters that the program expects to find in the configuration file.
expectedUsageMessage a simple message that lets the user understand how to properly run the
Returns
FacadeSingleton *
Definition at line 83 of file FacadeSingleton.cpp.
                                                                                                          {
    std::lock_guard <std::mutex> lock(singletonMutex);
    if (sharedInstance == nullptr) sharedInstance = new FacadeSingleton(expected_argc, expectedUsageMessage);
    return sharedInstance;
}
References expected_argc, expectedUsageMessage, FacadeSingleton(), sharedInstance, and singletonMutex.
getInstance() [2/2]
FacadeSingleton * FacadeSingleton::getInstance (void) [static]
Get the unique class instance. This methods should be called in the following scenario: when we just want to retrieve the reference to the object of this class.
Returns
FacadeSingleton *
Definition at line 89 of file FacadeSingleton.cpp.
                                                    {
    std::lock_guard <std::mutex> lock(singletonMutex);
    if (sharedInstance == nullptr) return nullptr;
    return sharedInstance;
}
References sharedInstance, and singletonMutex.
Referenced by Skeleton::calcBodyKeypoints(), Skeleton::deprojectSkeletonPoints3D(), Skeleton::generateSkeleton(), OpenCV_Manager::getVideoFramesCV(), main(), and OpenCV_Manager::showSkeletonsCV().
getKafkaManager()
KafkaManager * FacadeSingleton::getKafkaManager (void)
Get the KafkaManager pointer.
Returns
KafkaManager *
See also
KafkaManager.hpp
Definition at line 119 of file FacadeSingleton.cpp.
                                                     {
    return this->kafkaManager;
}
References kafkaManager.
Referenced by sendData(), and ~FacadeSingleton().
getOpenCV_Manager()
OpenCV_Manager * FacadeSingleton::getOpenCV_Manager (void)
Get the OpenCV_Manager pointer.
Returns
OpenCV_Manager *
See also
OpenCV_Manager.hpp
Definition at line 103 of file FacadeSingleton.cpp.
                                                         {
    return this->openCV_Manager;
}
References openCV_Manager.
Referenced by getVideoFrames(), showSkeletons(), and ~FacadeSingleton().
getOutputManager()
OutputManager * FacadeSingleton::getOutputManager (void)
Get the OutputManager pointer.
Returns
OutputManager *
See also
OutputManager.hpp
Definition at line 99 of file FacadeSingleton.cpp.
                                                       {
    return this->outputManager;
}
References outputManager.
Referenced by Skeleton::calcBodyKeypoints(), sendData(), OpenCV_Manager::showSkeletonsCV(), and ~FacadeSingleton().
getUsageManager()
UsageManager * FacadeSingleton::getUsageManager (void)
Get the UsageManager pointer.
Returns
UsageManager *
See also
UsageManager.hpp
Definition at line 107 of file FacadeSingleton.cpp.
                                                     {
    return this->usageManager;
}
References usageManager.
Referenced by cleanBuildFolder(), sendData(), OpenCV_Manager::showSkeletonsCV(), and ~FacadeSingleton().
getVideoBodyKeyPoints()
void FacadeSingleton::getVideoBodyKeyPoints (int * argc, char *** argv)
Start and execute OpenPose submodule.
Parameters
argc arguments' number specified on launch (from main).
argv arguments' specified on launch (from main).
See also
 https://cmu-perceptual-computing-lab.github.io/openpose/web/html/doc/md_doc_00_index.html
Definition at line 139 of file FacadeSingleton.cpp.
                                                                      {
    SystemCommand * openPoseCommand = new OpenPoseCommand();
    openPoseCommand->executeCommand(argc, argv);
    delete openPoseCommand;
}
References SystemCommand::executeCommand().
Referenced by main().
getVideoFrames()
void FacadeSingleton::getVideoFrames (unsigned int user_nFrame, rs2::pipeline & pipelineStream, float scale, const unsigned short int framesToSkip)
Get user_nFrame video frames from the pipeline by applying a specific scaling factor.
Parameters
user_nFrame frame's number to capture according to user choice.
pipelineStream The pipeline simplifies the user interaction with the device and computer vision processing modules. The class abstracts the camera configuration and streaming, and the vision modules triggering and threading. It lets the application focus on the computer vision output of the modules, or the device output data. The pipeline can manage computer vision modules, which are implemented as a processing block. The pipeline is the consumer of the processing block interface, while the application consumes the computer vision interface.
scale Scaling factor.
framesToSkip Frames' number to skip in order to ignore a certain amount of frames and extend the recording interval. A '0' value means 'capture each frame'.
See also
 https://dev.intelrealsense.com/docs/docs-get-started
getVideoFramesCV(unsigned int user_nFrame, rs2::pipeline & pipelineStream, float scale)
getVideoFramesRS(unsigned int user_nFrame, rs2::pipeline & pipelineStream, rs2::depth_frame & depthFrame, rs2::frame & colorFrame, rs2::frame & colorizedDepthFrame)
Definition at line 135 of file FacadeSingleton.cpp.
                                                                                                                                                {
    getOpenCV_Manager()->getVideoFramesCV(user_nFrame, pipelineStream, scale, framesToSkip);
}
References getOpenCV_Manager(), and OpenCV_Manager::getVideoFramesCV().
Referenced by main().
operator=()
void FacadeSingleton::operator= (const FacadeSingleton &) [delete]
Disabling the possibility to assign a Singleton object. Singletons should not be assignable.
sendData()
void FacadeSingleton::sendData (unsigned int user_nFrame)
Send saved results by getVideoBodyKeyPoints(...) via Kafka using the KafkaManager.
Parameters
user_nFrame frame's number to capture according to user choice.
See also
 https://kafka.apache.org/documentation/
sendData(const char * key, Json::Value root)
Definition at line 149 of file FacadeSingleton.cpp.
                                                        {
    char ** argv = * FacadeSingleton::getUsageManager()->get_argv(), * outputFolder = argv[outputFolderOffset];
    unsigned int frameID = FacadeSingleton::getCameraManager()->getFrameID(), currentImageID;
    OutputManagerJSON * myOutputManagerJSON = (OutputManagerJSON *) FacadeSingleton::getOutputManager();
    
    for (unsigned int nFrame = 0; nFrame < user_nFrame; nFrame++) {
        Json::Value currentJSON;
        std::stringstream outputJsonFilePath;
        currentImageID = frameID - user_nFrame + nFrame;
        outputJsonFilePath << outputFolder << "movement/frame" << currentImageID << "_skeletonsPoints3D.json";
        if (myOutputManagerJSON->loadJSON(outputJsonFilePath.str(), currentJSON)) {
            std::string key = std::to_string(currentImageID);
            FacadeSingleton::getKafkaManager()->sendData(key.c_str(), currentJSON);
        }
    }
}
References UsageManager::get_argv(), getCameraManager(), RealSenseManager::getFrameID(), getKafkaManager(), getOutputManager(), getUsageManager(), OutputManagerJSON::loadJSON(), outputFolderOffset, and KafkaManager::sendData().
Referenced by main().
setCameraManager()
void FacadeSingleton::setCameraManager (RealSenseManager * cameraManager) [protected]
Set the RealSenseManager pointer.
Parameters
cameraManager pointer to a RealSenseManager object.
See also
RealSenseManager.hpp
Definition at line 53 of file FacadeSingleton.cpp.
                                                                        {
    this->cameraManager = cameraManager;
}
References cameraManager.
Referenced by startEnvironment().
setCoordinateMappingManager()
void FacadeSingleton::setCoordinateMappingManager (CoordinateMappingManager * coordinateMappingManager) [protected]
Set the CoordinateMappingManager pointer.
Parameters
coordinateMappingManager pointer to an CoordinateMappingManager object.
See also
CoordinateMappingManager.hpp
Definition at line 69 of file FacadeSingleton.cpp.
                                                                                                      {
    this->coordinateMappingManager = coordinateMappingManager;
}
References coordinateMappingManager.
Referenced by startEnvironment().
setImageManager()
void FacadeSingleton::setImageManager (ImageManager * imageManager) [protected]
Set the ImageManager pointer.
Parameters
imageManager pointer to an ImageManager object.
See also
ImageManager.hpp
Definition at line 73 of file FacadeSingleton.cpp.
                                                                  {
    this->imageManager = imageManager;
}
References imageManager.
Referenced by startEnvironment().
setKafkaManager()
void FacadeSingleton::setKafkaManager (KafkaManager * kafkaManager) [protected]
Set the KafkaManager pointer.
Parameters
kafkaManager pointer to a KafkaManager object.
See also
KafkaManager.hpp
Definition at line 77 of file FacadeSingleton.cpp.
                                                                  {
    this->kafkaManager = kafkaManager;
}
References kafkaManager.
Referenced by startEnvironment().
setOpenCV_Manager()
void FacadeSingleton::setOpenCV_Manager (OpenCV_Manager * openCV_Manager) [protected]
Set the OpenCV_Manager pointer.
Parameters
openCV_Manager pointer to an OpenCV_Manager object.
See also
OpenCV_Manager.hpp
Definition at line 61 of file FacadeSingleton.cpp.
                                                                       {
    this->openCV_Manager = openCV_Manager;
}
References openCV_Manager.
Referenced by startEnvironment().
setOutputManager()
void FacadeSingleton::setOutputManager (OutputManager * outputManager) [protected]
Set the OutputManager pointer.
Parameters
outputManager pointer to an OutputManager object.
See also
OutputManager.hpp
Definition at line 57 of file FacadeSingleton.cpp.
                                                                     {
    this->outputManager = outputManager;
}
References outputManager.
Referenced by startEnvironment().
setUsageManager()
void FacadeSingleton::setUsageManager (UsageManager * usageManager) [protected]
Set the UsageManager pointer.
Parameters
usageManager pointer to an UsageManager object.
See also
UsageManager.hpp
Definition at line 65 of file FacadeSingleton.cpp.
                                                                 {
    this->usageManager = usageManager;
}
References usageManager.
Referenced by FacadeSingleton().
showSkeletons()
void FacadeSingleton::showSkeletons (unsigned int user_nFrame, const float skeletonThreshold)
Retrieve OpenPose's output, convert it to RealSense coordinate's space, show results and save them.
Parameters
user_nFrame frame's number to capture according to user choice.
skeletonThreshold The magnitude or intensity that must be exceeded for a specific reaction, phenomenon, result, or condition to occur or be manifested. In this case, if the skeleton's confidence mean value is greater than `skeletonThreshold`, then the skeleton will be considered a meaningful skeleton.
See also
showSkeletonsCV(unsigned int user_nFrame)
Definition at line 145 of file FacadeSingleton.cpp.
                                                                                            {
    getOpenCV_Manager()->showSkeletonsCV(user_nFrame, skeletonThreshold);
}
References getOpenCV_Manager(), and OpenCV_Manager::showSkeletonsCV().
Referenced by main().
startEnvironment()
void FacadeSingleton::startEnvironment (rs2::pipeline & pipelineStream, struct rs2_intrinsics & color_intrin, float * scale, unsigned short int resX, unsigned short int resY, const char * destinationKafkaTopic, Room room)
This method is useful to invoke at the boot of the program where we want to initialize the different mangers, start the camera and set up the related environment.
Parameters
pipelineStream The pipeline simplifies the user interaction with the device and computer vision processing modules. The class abstracts the camera configuration and streaming, and the vision modules triggering and threading. It lets the application focus on the computer vision output of the modules, or the device output data. The pipeline can manage computer vision modules, which are implemented as a processing block. The pipeline is the consumer of the processing block interface, while the application consumes the computer vision interface.
color_intrin Reference to color video stream intrinsics.
scale Pointer to scaling factor.
resX x resoultion <->.
resY y resolution.
destinationKafkaTopic the destination's kafka topic's name.
room Specific room within which the coordinate mapping will be done.
See also
 https://dev.intelrealsense.com/docs/docs-get-started
startEnvironment(rs2::pipeline & pipelineStream, struct rs2_intrinsics & color_intrin, float * scale, unsigned short int resX, unsigned short int resY, bool firstBoot)
Definition at line 123 of file FacadeSingleton.cpp.
                                                                                                                                                                                                                          {
    FacadeSingleton::setCameraManager(new RealSenseD435Manager());
    FacadeSingleton::setOutputManager(new OutputManagerJSON());
    FacadeSingleton::setOpenCV_Manager(new OpenCV_Manager());
    FacadeSingleton::setCoordinateMappingManager(new UnityCoordinateMappingManager(room));
    
    FacadeSingleton::setImageManager(new ImageManager());
    FacadeSingleton::setKafkaManager(new KafkaManager(destinationKafkaTopic));
    FacadeSingleton::getCameraManager()->startEnvironment(pipelineStream, color_intrin, scale, resX, resY, FIRST_BOOT);
    cleanBuildFolder();
}
References cleanBuildFolder(), FIRST_BOOT, getCameraManager(), setCameraManager(), setCoordinateMappingManager(), setImageManager(), setKafkaManager(), setOpenCV_Manager(), setOutputManager(), and RealSenseManager::startEnvironment().
Referenced by main().
Member Data Documentation
cameraManager
RealSenseManager* FacadeSingleton::cameraManager [private]
A pointer to RealSenseManager object. A RealSenseManager object is responsible for handling the camera setup, frames acquisition and frames post-processing.
See also
RealSenseManager.hpp
Definition at line 62 of file FacadeSingleton.hpp.
Referenced by getCameraManager(), and setCameraManager().
coordinateMappingManager
CoordinateMappingManager* FacadeSingleton::coordinateMappingManager [private]
A pointer to CoordinateMappingManager object. A CoordinateMappingManager object is responsible for transforming one coordinate range values' space into another one. For instance, it can transform a RealSense coordinates space to meters or to Unity coordinates. In both cases, there are several parameters to set up regarding the scene and the room where the camera is installed.
See also
constants.hpp
CoordinateMappingManager.hpp
Definition at line 90 of file FacadeSingleton.hpp.
Referenced by getCoordinateMappingManager(), and setCoordinateMappingManager().
imageManager
ImageManager* FacadeSingleton::imageManager [private]
A pointer to CoordinateMappingManager object. A CoordinateMappingManager object is responsible for broad tasks such as loading, saving, and showing images, as well as releasing the memory allocated for those images.
See also
ImageManager.hpp
Definition at line 97 of file FacadeSingleton.hpp.
Referenced by getImageManager(), and setImageManager().
kafkaManager
KafkaManager* FacadeSingleton::kafkaManager [private]
A pointer to KafkaManager object. A KafkaManager object is responsible for sending previously produced JSON output via Kafka.
See also
KafkaManager.hpp
Definition at line 103 of file FacadeSingleton.hpp.
Referenced by getKafkaManager(), and setKafkaManager().
openCV_Manager
OpenCV_Manager* FacadeSingleton::openCV_Manager [private]
A pointer to OpenCV_Manager object. An OpenCV_Manager object is responsible for converting camera frame to an OpenCV matrix and booting building skeletons into the image.
See also
OpenCV_Manager.hpp
Definition at line 74 of file FacadeSingleton.hpp.
Referenced by getOpenCV_Manager(), and setOpenCV_Manager().
outputManager
OutputManager* FacadeSingleton::outputManager [private]
A pointer to OutputManager object. An OutputManager object is responsible for handling the final output generation to send via Kafka later on.
See also
OutputManager.hpp
Definition at line 68 of file FacadeSingleton.hpp.
Referenced by getOutputManager(), and setOutputManager().
sharedInstance
FacadeSingleton * FacadeSingleton::sharedInstance { nullptr } [static], [private]
The field for storing the singleton instance.
Definition at line 49 of file FacadeSingleton.hpp.
Referenced by getInstance(), and ~FacadeSingleton().
singletonMutex
std::mutex FacadeSingleton::singletonMutex [static], [private]
Mutex for thread-safe access.
Definition at line 53 of file FacadeSingleton.hpp.
Referenced by getInstance().
usageManager
UsageManager* FacadeSingleton::usageManager [private]
A pointer to UsageManager object. An UsageManager object is responsible for checking if the parameters read from configuration file are fine, correct and valid. Furthermore this class provides methods to access this parameters.
See also
UsageManager.hpp
Definition at line 81 of file FacadeSingleton.hpp.
Referenced by getUsageManager(), and setUsageManager().
The documentation for this class was generated from the following files:
FacadeSingleton/FacadeSingleton.hpp
FacadeSingleton/FacadeSingleton.cpp