Room Class Reference
Room class represents the Room abstraction. A Room object has different specifications, such as width and height. Furthermore, since we are interested in the conversion from real-world coordinates to Unity coordinates, it's important to have some more informations, such as the axes' origins of the digital twin room and the camera's coordinates' interval value.
#include <Room.hpp>
Public Member Functions
Room (float minWidth, float maxWidth, float minHeight, float maxHeight, float maxDepth, float minWidthRS, float maxWidthRS, float minHeightRS, float maxHeightRS, float xOriginUnity, float zOriginUnity, float distanceCameraFromBackWall, float heightOffset)
Construct a new Room object.
float getMinWidth (void)
Get the Room's minimum width.
float getMaxWidth (void)
Get the Room's maximum width.
float getMinHeight (void)
Get the Room's minimum height.
float getMaxHeight (void)
Get the Room's maximum height.
float getMaxDepth (void)
Get the Room's maximum depth.
float getMinWidthRS (void)
Get the RealSense environment's minimum width.
float getMaxWidthRS (void)
Get the RealSense environment's maximum width.
float getMinHeightRS (void)
Get the RealSense environment's minimum height.
float getMaxHeightRS (void)
Get the RealSense environment's maximum height.
float getXOriginUnity (void)
Get the Ddgital twin's x axis' origin.
float getZOriginUnity (void)
Get the digital twin's z axis' origin.
float getDistanceCameraFromBackWall (void)
Get the distance between the camera lens and the wall back to the camera.
float getHeightOffset (void)
Get the height offset.
Protected Member Functions
void setMinWidth (float minWidth)
Set the Room's minimum width.
void setMaxWidth (float maxWidth)
Set the Room's maximum width.
void setMinHeight (float minHeight)
Set the Room's minimum height.
void setMaxHeight (float maxHeight)
Set the Room's maximum height.
void setMaxDepth (float maxHeight)
Set the Room's maximum depth.
void setMinWidthRS (float minWidthRS)
Set the RealSense environment's minimum width.
void setMaxWidthRS (float maxWidthRS)
Set the RealSense environment's maximum width.
void setMinHeightRS (float minHeightRS)
Set the RealSense environment's minimum height.
void setMaxHeightRS (float maxHeightRS)
Set the RealSense environment's maximum height.
void setXOriginUnity (float xOriginUnity)
Set the digital twin's x axis' origin.
void setZOriginUnity (float zOriginUnity)
Set the digital twin's z axis' origin.
void setDistanceCameraFromBackWall (float distanceCameraFromBackWall)
Set the distance between the camera lens and the wall back to the camera.
void setHeightOffset (float heightOffset)
Set the height offset.
Private Attributes
float _minWidth
Room's minimum width.
float _maxWidth
Room's maximum width.
float _minHeight
Room's minimum height.
float _maxHeight
Room's maximum height.
float _maxDepth
Room's maximum depth.
float _minWidthRS
RealSense environment's minimum width.
float _maxWidthRS
RealSense environment's maximum width.
float _minHeightRS
RealSense environment's minimum height.
float _maxHeightRS
RealSense environment's maximum height.
float _xOriginUnity
Digital twin's x axis' origin.
float _zOriginUnity
Digital twin's z axis' origin.
float _distanceCameraFromBackWall
Distance between the camera lens and the wall back to the camera.
float _heightOffset
Specific offset that is experimentally considered optimal in order to get more accurate height's measurements.
Detailed Description
Room class represents the Room abstraction. A Room object has different specifications, such as width and height. Furthermore, since we are interested in the conversion from real-world coordinates to Unity coordinates, it's important to have some more informations, such as the axes' origins of the digital twin room and the camera's coordinates' interval value.
Definition at line 64 of file Room.hpp.
Constructor & Destructor Documentation
Room()
Room::Room (float minWidth, float maxWidth, float minHeight, float maxHeight, float maxDepth, float minWidthRS, float maxWidthRS, float minHeightRS, float maxHeightRS, float xOriginUnity, float zOriginUnity, float distanceCameraFromBackWall, float heightOffset)
Construct a new Room object.
Parameters
minWidth Room's minimum width.
maxWidth Room's maximum width.
minHeight Room's minimum height.
maxHeight Room's maximum height.
minWidthRS RealSense environment's minimum width.
maxWidthRS RealSense environment's maximum width.
minHeightRS RealSense environment's minimum height.
maxHeightRS RealSense environment's maximum height.
xOriginUnity Digital twin's x axis' origin.
zOriginUnity Digital twin's z axis' origin.
distanceCameraFromBackWall Distance between the camera lens and the wall back to the camera.
heightOffset Specific offset that is experimentally considered optimal in order to get more accurate height's measurements.
Definition at line 67 of file Room.cpp.
                                                                                                    {
    setMinWidth(minWidth);
    setMaxWidth(maxWidth);
    setMinHeight(minHeight);
    setMaxHeight(maxHeight);
    setMaxDepth(maxDepth);
    setMinWidthRS(minWidthRS);
    setMaxWidthRS(maxWidthRS);
    setMinHeightRS(minHeightRS);
    setMaxHeightRS(maxHeightRS);
    setXOriginUnity(xOriginUnity);
    setZOriginUnity(zOriginUnity);
    setDistanceCameraFromBackWall(distanceCameraFromBackWall);
    setHeightOffset(heightOffset);
}
References distanceCameraFromBackWall, heightOffset, maxDepth, maxHeight, maxHeightRS, maxWidth, maxWidthRS, minHeight, minHeightRS, minWidthRS, setDistanceCameraFromBackWall(), setHeightOffset(), setMaxDepth(), setMaxHeight(), setMaxHeightRS(), setMaxWidth(), setMaxWidthRS(), setMinHeight(), setMinHeightRS(), setMinWidth(), setMinWidthRS(), setXOriginUnity(), setZOriginUnity(), xOriginUnity, and zOriginUnity.
Member Function Documentation
getDistanceCameraFromBackWall()
float Room::getDistanceCameraFromBackWall (void)
Get the distance between the camera lens and the wall back to the camera.
Returns
float
Definition at line 129 of file Room.cpp.
                                               {
    return this->_distanceCameraFromBackWall;
}
References _distanceCameraFromBackWall.
getHeightOffset()
float Room::getHeightOffset (void)
Get the height offset.
Returns
float
Definition at line 133 of file Room.cpp.
                                 {
    return this->_heightOffset;
}
References _heightOffset.
Referenced by CoordinateMappingManager::transformHeightCoordinate().
getMaxDepth()
float Room::getMaxDepth (void)
Get the Room's maximum depth.
Returns
float
Definition at line 101 of file Room.cpp.
                            {
    return this->_maxDepth;
}
References _maxDepth.
getMaxHeight()
float Room::getMaxHeight (void)
Get the Room's maximum height.
Returns
float
Definition at line 97 of file Room.cpp.
                              {
    return this->_maxHeight;
}
References _maxHeight.
Referenced by CoordinateMappingManager::transformHeightCoordinate().
getMaxHeightRS()
float Room::getMaxHeightRS (void)
Get the RealSense environment's maximum height.
Returns
float
Definition at line 117 of file Room.cpp.
                                {
    return this->_maxHeightRS;
}
References _maxHeightRS.
Referenced by CoordinateMappingManager::transformHeightCoordinate().
getMaxWidth()
float Room::getMaxWidth (void)
Get the Room's maximum width.
Returns
float
Definition at line 89 of file Room.cpp.
                             {
    return this->_maxWidth;
}
References _maxWidth.
getMaxWidthRS()
float Room::getMaxWidthRS (void)
Get the RealSense environment's maximum width.
Returns
float
Definition at line 109 of file Room.cpp.
                               {
    return this->_maxWidthRS;
}
References _maxWidthRS.
getMinHeight()
float Room::getMinHeight (void)
Get the Room's minimum height.
Returns
float
Definition at line 93 of file Room.cpp.
                              {
    return this->_minHeight;
}
References _minHeight.
getMinHeightRS()
float Room::getMinHeightRS (void)
Get the RealSense environment's minimum height.
Returns
float
Definition at line 113 of file Room.cpp.
                                {
    return this->_minHeightRS;
}
References _minHeightRS.
getMinWidth()
float Room::getMinWidth (void)
Get the Room's minimum width.
Returns
float
Definition at line 85 of file Room.cpp.
                             {
    return this->_minWidth;
}
References _minWidth.
Referenced by CoordinateMappingManager::transformWidthCoordinate().
getMinWidthRS()
float Room::getMinWidthRS (void)
Get the RealSense environment's minimum width.
Returns
float
Definition at line 105 of file Room.cpp.
                               {
    return this->_minWidthRS;
}
References _minWidthRS.
getXOriginUnity()
float Room::getXOriginUnity (void)
Get the Ddgital twin's x axis' origin.
Returns
float
Definition at line 121 of file Room.cpp.
                                 {
    return this->_xOriginUnity;
}
References _xOriginUnity.
getZOriginUnity()
float Room::getZOriginUnity (void)
Get the digital twin's z axis' origin.
Returns
float
Definition at line 125 of file Room.cpp.
                                 {
    return this->_zOriginUnity;
}
References _zOriginUnity.
setDistanceCameraFromBackWall()
void Room::setDistanceCameraFromBackWall (float distanceCameraFromBackWall) [protected]
Set the distance between the camera lens and the wall back to the camera.
Parameters
distanceCameraFromBackWall Distance between the camera lens and the wall back to the camera.
Definition at line 57 of file Room.cpp.
                                                                          {
    this->_distanceCameraFromBackWall = distanceCameraFromBackWall;
}
References _distanceCameraFromBackWall, and distanceCameraFromBackWall.
Referenced by Room().
setHeightOffset()
void Room::setHeightOffset (float heightOffset) [protected]
Set the height offset.
Parameters
heightOffset Specific offset that is experimentally considered optimal in order to get more accurate height's measurements.
Definition at line 61 of file Room.cpp.
                                              {
    this->_heightOffset = heightOffset;
}
References _heightOffset, and heightOffset.
Referenced by Room().
setMaxDepth()
void Room::setMaxDepth (float maxHeight) [protected]
Set the Room's maximum depth.
Parameters
maxHeight Room's maximum depth.
Definition at line 29 of file Room.cpp.
                                     {
    this->_maxDepth = maxDepth;
}
References _maxDepth, and maxDepth.
Referenced by Room().
setMaxHeight()
void Room::setMaxHeight (float maxHeight) [protected]
Set the Room's maximum height.
Parameters
maxHeight Room's maximum height.
Definition at line 25 of file Room.cpp.
                                        {
    this->_maxHeight = maxHeight;
}
References _maxHeight, and maxHeight.
Referenced by Room().
setMaxHeightRS()
void Room::setMaxHeightRS (float maxHeightRS) [protected]
Set the RealSense environment's maximum height.
Parameters
maxHeightRS RealSense environment's maximum height.
Definition at line 45 of file Room.cpp.
                                            {
    this->_maxHeightRS = maxHeightRS;
}
References _maxHeightRS, and maxHeightRS.
Referenced by Room().
setMaxWidth()
void Room::setMaxWidth (float maxWidth) [protected]
Set the Room's maximum width.
Parameters
maxWidth Room's maximum width.
Definition at line 17 of file Room.cpp.
                                      {
    this->_maxWidth = maxWidth;
}
References _maxWidth, and maxWidth.
Referenced by Room().
setMaxWidthRS()
void Room::setMaxWidthRS (float maxWidthRS) [protected]
Set the RealSense environment's maximum width.
Parameters
maxWidthRS RealSense environment's maximum width.
Definition at line 37 of file Room.cpp.
                                          {
    this->_maxWidthRS = maxWidthRS;
}
References _maxWidthRS, and maxWidthRS.
Referenced by Room().
setMinHeight()
void Room::setMinHeight (float minHeight) [protected]
Set the Room's minimum height.
Parameters
minHeight Room's minimum height.
Definition at line 21 of file Room.cpp.
                                        {
    this->_minHeight = minHeight;
}
References _minHeight, and minHeight.
Referenced by Room().
setMinHeightRS()
void Room::setMinHeightRS (float minHeightRS) [protected]
Set the RealSense environment's minimum height.
Parameters
minHeightRS RealSense environment's minimum height.
Definition at line 41 of file Room.cpp.
                                            {
    this->_minHeightRS = minHeightRS;
}
References _minHeightRS, and minHeightRS.
Referenced by Room().
setMinWidth()
void Room::setMinWidth (float minWidth) [protected]
Set the Room's minimum width.
Parameters
minWidth Room's minimum width.
Definition at line 13 of file Room.cpp.
                                      {
    this->_minWidth = minWidth;
}
References _minWidth, and minWidth.
Referenced by Room().
setMinWidthRS()
void Room::setMinWidthRS (float minWidthRS) [protected]
Set the RealSense environment's minimum width.
Parameters
minWidthRS RealSense environment's minimum width.
Definition at line 33 of file Room.cpp.
                                          {
    this->_minWidthRS = minWidthRS;
}
References _minWidthRS, and minWidthRS.
Referenced by Room().
setXOriginUnity()
void Room::setXOriginUnity (float xOriginUnity) [protected]
Set the digital twin's x axis' origin.
Parameters
xOriginUnity Digital twin's x axis' origin.
Definition at line 49 of file Room.cpp.
                                              {
    this->_xOriginUnity = xOriginUnity;
}
References _xOriginUnity, and xOriginUnity.
Referenced by Room().
setZOriginUnity()
void Room::setZOriginUnity (float zOriginUnity) [protected]
Set the digital twin's z axis' origin.
Parameters
zOriginUnity Digital twin's z axis' origin.
Definition at line 53 of file Room.cpp.
                                                 {
    this->_zOriginUnity = zOriginUnity;
}
References _zOriginUnity, and zOriginUnity.
Referenced by Room().
Member Data Documentation
_distanceCameraFromBackWall
float Room::_distanceCameraFromBackWall [private]
Distance between the camera lens and the wall back to the camera.
Definition at line 117 of file Room.hpp.
Referenced by getDistanceCameraFromBackWall(), and setDistanceCameraFromBackWall().
_heightOffset
float Room::_heightOffset [private]
Specific offset that is experimentally considered optimal in order to get more accurate height's measurements.
Definition at line 122 of file Room.hpp.
Referenced by getHeightOffset(), and setHeightOffset().
_maxDepth
float Room::_maxDepth [private]
Room's maximum depth.
Definition at line 85 of file Room.hpp.
Referenced by getMaxDepth(), and setMaxDepth().
_maxHeight
float Room::_maxHeight [private]
Room's maximum height.
Definition at line 81 of file Room.hpp.
Referenced by getMaxHeight(), and setMaxHeight().
_maxHeightRS
float Room::_maxHeightRS [private]
RealSense environment's maximum height.
Definition at line 102 of file Room.hpp.
Referenced by getMaxHeightRS(), and setMaxHeightRS().
_maxWidth
float Room::_maxWidth [private]
Room's maximum width.
Definition at line 73 of file Room.hpp.
Referenced by getMaxWidth(), and setMaxWidth().
_maxWidthRS
float Room::_maxWidthRS [private]
RealSense environment's maximum width.
Definition at line 94 of file Room.hpp.
Referenced by getMaxWidthRS(), and setMaxWidthRS().
_minHeight
float Room::_minHeight [private]
Room's minimum height.
Definition at line 77 of file Room.hpp.
Referenced by getMinHeight(), and setMinHeight().
_minHeightRS
float Room::_minHeightRS [private]
RealSense environment's minimum height.
Definition at line 98 of file Room.hpp.
Referenced by getMinHeightRS(), and setMinHeightRS().
_minWidth
float Room::_minWidth [private]
Room's minimum width.
Definition at line 69 of file Room.hpp.
Referenced by getMinWidth(), and setMinWidth().
_minWidthRS
float Room::_minWidthRS [private]
RealSense environment's minimum width.
Definition at line 90 of file Room.hpp.
Referenced by getMinWidthRS(), and setMinWidthRS().
_xOriginUnity
float Room::_xOriginUnity [private]
Digital twin's x axis' origin.
Definition at line 108 of file Room.hpp.
Referenced by getXOriginUnity(), and setXOriginUnity().
_zOriginUnity
float Room::_zOriginUnity [private]
Digital twin's z axis' origin.
Definition at line 112 of file Room.hpp.
Referenced by getZOriginUnity(), and setZOriginUnity().
The documentation for this class was generated from the following files:
Room/Room.hpp
Room/Room.cpp