CleanCommand Class Reference
The CleanCommand class is a class that implements a command to clean the build folder by deleting old files.
#include <SystemCommand.hpp>
Public Member Functions
void executeCommand (int *argc, char ***argv)
This method is responsible for executing commands on the system based on the filled command string. If the string is empty, then no command is executed.
Protected Member Functions
void setCommand (int *argc, char ***argv) override
Set the string command to a cleaning command.
void setCommand (std::string command)
Set the string command with a particularly given string passed as a parameter.
std::string getCommand (void)
Get the string command.
Private Attributes
std::string command
The final command given to the system by the program.
Detailed Description
The CleanCommand class is a class that implements a command to clean the build folder by deleting old files.
The CleanCommand class is a class that implements a command to clean the build folder by deleting old files. It deletes all the images captured and computed when the current `JSONs' sending session with Kafka` is completed, as well as it deletes all the JSONs files produced in the meanwhile.
Definition at line 73 of file SystemCommand.hpp.
Member Function Documentation
executeCommand()
void SystemCommand::executeCommand (int * argc, char *** argv) [inherited]
This method is responsible for executing commands on the system based on the filled command string. If the string is empty, then no command is executed.
Parameters
argc pointer to argc from the main function or based on what the program reads from the configuration file.
argv pointer to argv from the main function or based on what the program reads from the configuration file.
Definition at line 23 of file SystemCommand.cpp.
                                                             {
    setCommand(argc, argv);
    if (getCommand().size() > 0 && getCommand() != "OP") std::system(getCommand().c_str());
}
References SystemCommand::getCommand(), and SystemCommand::setCommand().
Referenced by FacadeSingleton::cleanBuildFolder(), and FacadeSingleton::getVideoBodyKeyPoints().
getCommand()
std::string SystemCommand::getCommand (void) [protected], [inherited]
Get the string command.
Returns
std::string
Definition at line 19 of file SystemCommand.cpp.
                                         {
    return this->command;
}
References SystemCommand::command.
Referenced by SystemCommand::executeCommand().
setCommand() [1/2]
void CleanCommand::setCommand (int * argc, char *** argv) [override], [protected], [virtual]
Set the string command to a cleaning command.
Parameters
argc pointer to argc based on what the program reads from the configuration file.
argv pointer to argv based on what the program reads from the configuration file.
Implements SystemCommand.
Definition at line 15 of file CleanCommand.cpp.
                                                        {
    std::stringstream cleanTerminalCommand;
    UsageManager * usageManagerInstance = UsageManager::getInstance();
    if (usageManagerInstance == nullptr) CV_Error(USAGE_MANAGER_NULLPTR_ERROR, USAGE_MANAGER_NULLPTR_SCOPE);
    
    char *** localArgv = usageManagerInstance->get_argv();
    const char * imagesFolder = (* localArgv)[imagesFolderOffset];
    const char * outputFolder = (* localArgv)[outputFolderOffset];
    cleanTerminalCommand << "rm -r " << imagesFolder << "rgb/ > /dev/null && "
                            "rm -r " << imagesFolder << "d/ > /dev/null && "
                            "rm -r " << imagesFolder << "skeleton/ > /dev/null && "
                            "rm -r " << imagesFolder << "videoframe/ > /dev/null && "
                            "rm -r " << outputFolder << "op/ > /dev/null && "
                            "rm -r " << imagesFolder << "depth/ > /dev/null && "
                            "rm -r " << imagesFolder << "sk/ > /dev/null && "
                            "rm -r " << outputFolder << "movement/ > /dev/null && "
                            "mkdir " << imagesFolder << "rgb && "
                            "mkdir " << imagesFolder << "d && "
                            "mkdir " << imagesFolder << "videoframe && "
                            "mkdir " << imagesFolder << "skeleton && "
                            "mkdir " << imagesFolder << "depth && "
                            "mkdir " << imagesFolder << "sk && "
                            "mkdir " << outputFolder << "movement/ && "
                            "mkdir " << outputFolder << "op/";
    SystemCommand::setCommand(std::string(cleanTerminalCommand.str()));
}
References UsageManager::get_argv(), UsageManager::getInstance(), imagesFolderOffset, outputFolderOffset, SystemCommand::setCommand(), USAGE_MANAGER_NULLPTR_ERROR, and USAGE_MANAGER_NULLPTR_SCOPE.
setCommand() [2/2]
void SystemCommand::setCommand (std::string command) [protected], [inherited]
Set the string command with a particularly given string passed as a parameter.
Parameters
command
Definition at line 15 of file SystemCommand.cpp.
                                                 {
    this->command = command;
}
References SystemCommand::command.
Member Data Documentation
command
std::string SystemCommand::command [private], [inherited]
The final command given to the system by the program.
Definition at line 33 of file SystemCommand.hpp.
Referenced by SystemCommand::getCommand(), and SystemCommand::setCommand().
The documentation for this class was generated from the following files:
Command/SystemCommand.hpp
Command/CleanCommand.cpp