BodyKeyPoint Class Reference
BodyKeyPoint class is used for body keypoint creations and manipulations.
#include <BodyKeyPoint.hpp>
Public Member Functions
BodyKeyPoint (float x, float y, float confidence, Point *decorated=nullptr)
Construct a new Body Keypoint object.
float getConfidence (void)
Get the confidence value.
float getX (void)
Get the Point's x coordinate value.
float getY (void)
Get the Point's y coordinate value.
const Point * getDecorated (void)
Get the pointer to Point used to check if that's a `decorated` Point.
Protected Member Functions
void setX (float x)
Set the Point's x coordinate value.
void setY (float y)
Set the Point's y coordinate value.
Private Member Functions
void setConfidence (float confidence)
Set the confidence value.
Private Attributes
float confidence
The confidence value is an OpenPose parameter to evaluate how accurate the process was while determining this particular joint point.
float x
Point's x coordinate.
float y
Point's y coordinate.
const Point * decorated
A pointer to Point.
Detailed Description
BodyKeyPoint class is used for body keypoint creations and manipulations.
BodyKeyPoint class is a class that represents a Body Keypoint with its own x coordinate and y coordinate. This class inherits from Point and adds the `confidence` detail in order to keep track of the OpenPose confidence on this particular point.
Definition at line 24 of file BodyKeyPoint.hpp.
Constructor & Destructor Documentation
BodyKeyPoint()
BodyKeyPoint::BodyKeyPoint (float x, float y, float confidence, Point * decorated = nullptr)
Construct a new Body Keypoint object.
Parameters
x
y
confidence
decorated
See also
Point (float x, float y, Point * decorated = nullptr) : decorated(decorated)
Definition at line 21 of file BodyKeyPoint.cpp.
                                                                                 : Point(x, y, decorated) {
    setConfidence(confidence);
}
References confidence, and setConfidence().
Member Function Documentation
getConfidence()
float BodyKeyPoint::getConfidence (void)
Get the confidence value.
Returns
float
Definition at line 25 of file BodyKeyPoint.cpp.
                                       {
    return this->confidence;
}
References confidence.
getDecorated()
const Point * Point::getDecorated (void) [inherited]
Get the pointer to Point used to check if that's a `decorated` Point.
Returns
const Point *
Definition at line 37 of file Point.cpp.
                                       {
    return this->decorated;
}
References Point::decorated.
Referenced by Point::~Point().
getX()
float Point::getX (void) [inherited]
Get the Point's x coordinate value.
Returns
float
Definition at line 29 of file Point.cpp.
                       {
    return this->x;
}
References Point::x.
getY()
float Point::getY (void) [inherited]
Get the Point's y coordinate value.
Returns
float
Definition at line 33 of file Point.cpp.
                       {
    return this->y;
}
References Point::y.
setConfidence()
void BodyKeyPoint::setConfidence (float confidence) [private]
Set the confidence value.
Parameters
confidence
Definition at line 15 of file BodyKeyPoint.cpp.
                                                  {
    this->confidence = confidence;
}
References confidence.
Referenced by BodyKeyPoint().
setX()
void Point::setX (float x) [protected], [inherited]
Set the Point's x coordinate value.
Parameters
x Point's x coordinate value.
Definition at line 15 of file Point.cpp.
                         {
    this->x = x;
}
References Point::x.
Referenced by Point::Point().
setY()
void Point::setY (float y) [protected], [inherited]
Set the Point's y coordinate value.
Parameters
y Point's y coordinate value.
Definition at line 19 of file Point.cpp.
                         {
    this->y = y;
}
References Point::y.
Referenced by Point::Point().
Member Data Documentation
confidence
float BodyKeyPoint::confidence [private]
The confidence value is an OpenPose parameter to evaluate how accurate the process was while determining this particular joint point.
Definition at line 30 of file BodyKeyPoint.hpp.
Referenced by BodyKeyPoint(), getConfidence(), and setConfidence().
decorated
const Point* Point::decorated [private], [inherited]
A pointer to Point.
Definition at line 34 of file Point.hpp.
Referenced by Point::getDecorated().
x
float Point::x [private], [inherited]
Point's x coordinate.
Definition at line 26 of file Point.hpp.
Referenced by Point::getX(), Point::Point(), and Point::setX().
y
float Point::y [private], [inherited]
Point's y coordinate.
Definition at line 30 of file Point.hpp.
Referenced by Point::getY(), Point::Point(), and Point::setY().
The documentation for this class was generated from the following files:
Points/BodyKeyPoint.hpp
Points/BodyKeyPoint.cpp