SystemCommand Class Reference
SystemCommand class is a class that represents a command given by the program to the system.
#include <SystemCommand.hpp>
Public Member Functions
virtual ~SystemCommand ()=default
Destroy the SystemCommand object.
void executeCommand (int *argc, char ***argv)
This method is responsible for executing commands on the system based on the filled command string. If the string is empty, then no command is executed.
Protected Member Functions
virtual void setCommand (int *argc, char ***argv)=0
Set the string command. The method is inherited from the subclasses and overridden in order to express a specific behavior.
void setCommand (std::string command)
Set the string command with a particularly given string passed as a parameter.
std::string getCommand (void)
Get the string command.
Private Attributes
std::string command
The final command given to the system by the program.
Detailed Description
SystemCommand class is a class that represents a command given by the program to the system.
SystemCommand class is a class that represents a command given by the program to the system. Examples of commands are the following: start and run OpenPose, move files, and clean the build folder by deleting old files. SystemCommand implements a variant of the Command design pattern. Each concrete command is realized by a specific subclass that implements the parent abstract method.
Definition at line 28 of file SystemCommand.hpp.
Constructor & Destructor Documentation
 SystemCommand()
virtual SystemCommand::~SystemCommand () [virtual], [default]
Destroy the SystemCommand object.
Member Function Documentation
executeCommand()
void SystemCommand::executeCommand (int * argc, char *** argv)
This method is responsible for executing commands on the system based on the filled command string. If the string is empty, then no command is executed.
Parameters
argc pointer to argc from the main function or based on what the program reads from the configuration file.
argv pointer to argv from the main function or based on what the program reads from the configuration file.
Definition at line 23 of file SystemCommand.cpp.
                                                             {
    setCommand(argc, argv);
    if (getCommand().size() > 0 && getCommand() != "OP") std::system(getCommand().c_str());
}
References getCommand(), and setCommand().
Referenced by FacadeSingleton::cleanBuildFolder(), and FacadeSingleton::getVideoBodyKeyPoints().
getCommand()
std::string SystemCommand::getCommand (void) [protected]
Get the string command.
Returns
std::string
Definition at line 19 of file SystemCommand.cpp.
                                         {
    return this->command;
}
References command.
Referenced by executeCommand().
setCommand() [1/2]
virtual void SystemCommand::setCommand (int * argc, char *** argv) [protected], [pure virtual]
Set the string command. The method is inherited from the subclasses and overridden in order to express a specific behavior.
Parameters
argc pointer to argc based on what program reads from configuration file.
argv pointer to argv based on what program reads from configuration file.
Implemented in CleanCommand, OpenPoseCommand, and MoveCommand.
Referenced by executeCommand(), CleanCommand::setCommand(), OpenPoseCommand::setCommand(), and MoveCommand::setCommand().
setCommand() [2/2]
void SystemCommand::setCommand (std::string command) [protected]
Set the string command with a particularly given string passed as a parameter.
Parameters
command
Definition at line 15 of file SystemCommand.cpp.
                                                 {
    this->command = command;
}
References command.
Member Data Documentation
command
std::string SystemCommand::command [private]
The final command given to the system by the program.
Definition at line 33 of file SystemCommand.hpp.
Referenced by getCommand(), and setCommand().
The documentation for this class was generated from the following files:
Command/SystemCommand.hpp
Command/SystemCommand.cpp