CVPR_Lab Class Reference
CVPR Lab class represents the CVPR Lab abstraction. The CVPR Lab is a Room with default values. Those default values are the ones above. Meanwhile, a Room object lets the possibility to define a room with custom dimensions. The real CVPR Lab is located at University of Naples Parthenope, Italy.
#include <CVPR_Lab.hpp>
Public Member Functions
CVPR_Lab (void)
Construct a new CVPR Lab object.
float getMinWidth (void)
Get the Room's minimum width.
float getMaxWidth (void)
Get the Room's maximum width.
float getMinHeight (void)
Get the Room's minimum height.
float getMaxHeight (void)
Get the Room's maximum height.
float getMaxDepth (void)
Get the Room's maximum depth.
float getMinWidthRS (void)
Get the RealSense environment's minimum width.
float getMaxWidthRS (void)
Get the RealSense environment's maximum width.
float getMinHeightRS (void)
Get the RealSense environment's minimum height.
float getMaxHeightRS (void)
Get the RealSense environment's maximum height.
float getXOriginUnity (void)
Get the Ddgital twin's x axis' origin.
float getZOriginUnity (void)
Get the digital twin's z axis' origin.
float getDistanceCameraFromBackWall (void)
Get the distance between the camera lens and the wall back to the camera.
float getHeightOffset (void)
Get the height offset.
Protected Member Functions
void setMinWidth (float minWidth)
Set the Room's minimum width.
void setMaxWidth (float maxWidth)
Set the Room's maximum width.
void setMinHeight (float minHeight)
Set the Room's minimum height.
void setMaxHeight (float maxHeight)
Set the Room's maximum height.
void setMaxDepth (float maxHeight)
Set the Room's maximum depth.
void setMinWidthRS (float minWidthRS)
Set the RealSense environment's minimum width.
void setMaxWidthRS (float maxWidthRS)
Set the RealSense environment's maximum width.
void setMinHeightRS (float minHeightRS)
Set the RealSense environment's minimum height.
void setMaxHeightRS (float maxHeightRS)
Set the RealSense environment's maximum height.
void setXOriginUnity (float xOriginUnity)
Set the digital twin's x axis' origin.
void setZOriginUnity (float zOriginUnity)
Set the digital twin's z axis' origin.
void setDistanceCameraFromBackWall (float distanceCameraFromBackWall)
Set the distance between the camera lens and the wall back to the camera.
void setHeightOffset (float heightOffset)
Set the height offset.
Private Attributes
float _minWidth
Room's minimum width.
float _maxWidth
Room's maximum width.
float _minHeight
Room's minimum height.
float _maxHeight
Room's maximum height.
float _maxDepth
Room's maximum depth.
float _minWidthRS
RealSense environment's minimum width.
float _maxWidthRS
RealSense environment's maximum width.
float _minHeightRS
RealSense environment's minimum height.
float _maxHeightRS
RealSense environment's maximum height.
float _xOriginUnity
Digital twin's x axis' origin.
float _zOriginUnity
Digital twin's z axis' origin.
float _distanceCameraFromBackWall
Distance between the camera lens and the wall back to the camera.
float _heightOffset
Specific offset that is experimentally considered optimal in order to get more accurate height's measurements.
Detailed Description
CVPR Lab class represents the CVPR Lab abstraction. The CVPR Lab is a Room with default values. Those default values are the ones above. Meanwhile, a Room object lets the possibility to define a room with custom dimensions. The real CVPR Lab is located at University of Naples Parthenope, Italy.
Definition at line 23 of file CVPR_Lab.hpp.
Constructor & Destructor Documentation
CVPR_Lab()
CVPR_Lab::CVPR_Lab (void)
Construct a new CVPR Lab object.
Definition at line 15 of file CVPR_Lab.cpp.
: Room(minWidth, maxWidth, minHeight, maxHeight, maxDepth, minWidthRS, maxWidthRS, minHeightRS, maxHeightRS, xOriginUnity, zOriginUnity, distanceCameraFromBackWall, heightOffset) { }
Member Function Documentation
getDistanceCameraFromBackWall()
float Room::getDistanceCameraFromBackWall (void) [inherited]
Get the distance between the camera lens and the wall back to the camera.
Returns
float
Definition at line 129 of file Room.cpp.
                                               {
    return this->_distanceCameraFromBackWall;
}
References Room::_distanceCameraFromBackWall.
getHeightOffset()
float Room::getHeightOffset (void) [inherited]
Get the height offset.
Returns
float
Definition at line 133 of file Room.cpp.
                                 {
    return this->_heightOffset;
}
References Room::_heightOffset.
Referenced by CoordinateMappingManager::transformHeightCoordinate().
getMaxDepth()
float Room::getMaxDepth (void) [inherited]
Get the Room's maximum depth.
Returns
float
Definition at line 101 of file Room.cpp.
                            {
    return this->_maxDepth;
}
References Room::_maxDepth.
getMaxHeight()
float Room::getMaxHeight (void) [inherited]
Get the Room's maximum height.
Returns
float
Definition at line 97 of file Room.cpp.
                              {
    return this->_maxHeight;
}
References Room::_maxHeight.
Referenced by CoordinateMappingManager::transformHeightCoordinate().
getMaxHeightRS()
float Room::getMaxHeightRS (void) [inherited]
Get the RealSense environment's maximum height.
Returns
float
Definition at line 117 of file Room.cpp.
                                {
    return this->_maxHeightRS;
}
References Room::_maxHeightRS.
Referenced by CoordinateMappingManager::transformHeightCoordinate().
getMaxWidth()
float Room::getMaxWidth (void) [inherited]
Get the Room's maximum width.
Returns
float
Definition at line 89 of file Room.cpp.
                             {
    return this->_maxWidth;
}
References Room::_maxWidth.
getMaxWidthRS()
float Room::getMaxWidthRS (void) [inherited]
Get the RealSense environment's maximum width.
Returns
float
Definition at line 109 of file Room.cpp.
                               {
    return this->_maxWidthRS;
}
References Room::_maxWidthRS.
getMinHeight()
float Room::getMinHeight (void) [inherited]
Get the Room's minimum height.
Returns
float
Definition at line 93 of file Room.cpp.
                              {
    return this->_minHeight;
}
References Room::_minHeight.
getMinHeightRS()
float Room::getMinHeightRS (void) [inherited]
Get the RealSense environment's minimum height.
Returns
float
Definition at line 113 of file Room.cpp.
                                {
    return this->_minHeightRS;
}
References Room::_minHeightRS.
getMinWidth()
float Room::getMinWidth (void) [inherited]
Get the Room's minimum width.
Returns
float
Definition at line 85 of file Room.cpp.
                             {
    return this->_minWidth;
}
References Room::_minWidth.
Referenced by CoordinateMappingManager::transformWidthCoordinate().
getMinWidthRS()
float Room::getMinWidthRS (void) [inherited]
Get the RealSense environment's minimum width.
Returns
float
Definition at line 105 of file Room.cpp.
                               {
    return this->_minWidthRS;
}
References Room::_minWidthRS.
getXOriginUnity()
float Room::getXOriginUnity (void) [inherited]
Get the Ddgital twin's x axis' origin.
Returns
float
Definition at line 121 of file Room.cpp.
                                 {
    return this->_xOriginUnity;
}
References Room::_xOriginUnity.
getZOriginUnity()
float Room::getZOriginUnity (void) [inherited]
Get the digital twin's z axis' origin.
Returns
float
Definition at line 125 of file Room.cpp.
                                 {
    return this->_zOriginUnity;
}
References Room::_zOriginUnity.
setDistanceCameraFromBackWall()
void Room::setDistanceCameraFromBackWall (float distanceCameraFromBackWall) [protected], [inherited]
Set the distance between the camera lens and the wall back to the camera.
Parameters
distanceCameraFromBackWall Distance between the camera lens and the wall back to the camera.
Definition at line 57 of file Room.cpp.
                                                                          {
    this->_distanceCameraFromBackWall = distanceCameraFromBackWall;
}
References Room::_distanceCameraFromBackWall, and distanceCameraFromBackWall.
Referenced by Room::Room().
setHeightOffset()
void Room::setHeightOffset (float heightOffset) [protected], [inherited]
Set the height offset.
Parameters
heightOffset Specific offset that is experimentally considered optimal in order to get more accurate height's measurements.
Definition at line 61 of file Room.cpp.
                                              {
    this->_heightOffset = heightOffset;
}
References Room::_heightOffset, and heightOffset.
Referenced by Room::Room().
setMaxDepth()
void Room::setMaxDepth (float maxHeight) [protected], [inherited]
Set the Room's maximum depth.
Parameters
maxHeight Room's maximum depth.
Definition at line 29 of file Room.cpp.
                                     {
    this->_maxDepth = maxDepth;
}
References Room::_maxDepth, and maxDepth.
Referenced by Room::Room().
setMaxHeight()
void Room::setMaxHeight (float maxHeight) [protected], [inherited]
Set the Room's maximum height.
Parameters
maxHeight Room's maximum height.
Definition at line 25 of file Room.cpp.
                                        {
    this->_maxHeight = maxHeight;
}
References Room::_maxHeight, and maxHeight.
Referenced by Room::Room().
setMaxHeightRS()
void Room::setMaxHeightRS (float maxHeightRS) [protected], [inherited]
Set the RealSense environment's maximum height.
Parameters
maxHeightRS RealSense environment's maximum height.
Definition at line 45 of file Room.cpp.
                                            {
    this->_maxHeightRS = maxHeightRS;
}
References Room::_maxHeightRS, and maxHeightRS.
Referenced by Room::Room().
setMaxWidth()
void Room::setMaxWidth (float maxWidth) [protected], [inherited]
Set the Room's maximum width.
Parameters
maxWidth Room's maximum width.
Definition at line 17 of file Room.cpp.
                                      {
    this->_maxWidth = maxWidth;
}
References Room::_maxWidth, and maxWidth.
Referenced by Room::Room().
setMaxWidthRS()
void Room::setMaxWidthRS (float maxWidthRS) [protected], [inherited]
Set the RealSense environment's maximum width.
Parameters
maxWidthRS RealSense environment's maximum width.
Definition at line 37 of file Room.cpp.
                                          {
    this->_maxWidthRS = maxWidthRS;
}
References Room::_maxWidthRS, and maxWidthRS.
Referenced by Room::Room().
setMinHeight()
void Room::setMinHeight (float minHeight) [protected], [inherited]
Set the Room's minimum height.
Parameters
minHeight Room's minimum height.
Definition at line 21 of file Room.cpp.
                                        {
    this->_minHeight = minHeight;
}
References Room::_minHeight, and minHeight.
Referenced by Room::Room().
setMinHeightRS()
void Room::setMinHeightRS (float minHeightRS) [protected], [inherited]
Set the RealSense environment's minimum height.
Parameters
minHeightRS RealSense environment's minimum height.
Definition at line 41 of file Room.cpp.
                                            {
    this->_minHeightRS = minHeightRS;
}
References Room::_minHeightRS, and minHeightRS.
Referenced by Room::Room().
setMinWidth()
void Room::setMinWidth (float minWidth) [protected], [inherited]
Set the Room's minimum width.
Parameters
minWidth Room's minimum width.
Definition at line 13 of file Room.cpp.
                                      {
    this->_minWidth = minWidth;
}
References Room::_minWidth, and minWidth.
Referenced by Room::Room().
setMinWidthRS()
void Room::setMinWidthRS (float minWidthRS) [protected], [inherited]
Set the RealSense environment's minimum width.
Parameters
minWidthRS RealSense environment's minimum width.
Definition at line 33 of file Room.cpp.
                                          {
    this->_minWidthRS = minWidthRS;
}
References Room::_minWidthRS, and minWidthRS.
Referenced by Room::Room().
setXOriginUnity()
void Room::setXOriginUnity (float xOriginUnity) [protected], [inherited]
Set the digital twin's x axis' origin.
Parameters
xOriginUnity Digital twin's x axis' origin.
Definition at line 49 of file Room.cpp.
                                              {
    this->_xOriginUnity = xOriginUnity;
}
References Room::_xOriginUnity, and xOriginUnity.
Referenced by Room::Room().
setZOriginUnity()
void Room::setZOriginUnity (float zOriginUnity) [protected], [inherited]
Set the digital twin's z axis' origin.
Parameters
zOriginUnity Digital twin's z axis' origin.
Definition at line 53 of file Room.cpp.
                                                 {
    this->_zOriginUnity = zOriginUnity;
}
References Room::_zOriginUnity, and zOriginUnity.
Referenced by Room::Room().
Member Data Documentation
_distanceCameraFromBackWall
float Room::_distanceCameraFromBackWall [private], [inherited]
Distance between the camera lens and the wall back to the camera.
Definition at line 117 of file Room.hpp.
Referenced by Room::getDistanceCameraFromBackWall(), and Room::setDistanceCameraFromBackWall().
_heightOffset
float Room::_heightOffset [private], [inherited]
Specific offset that is experimentally considered optimal in order to get more accurate height's measurements.
Definition at line 122 of file Room.hpp.
Referenced by Room::getHeightOffset(), and Room::setHeightOffset().
_maxDepth
float Room::_maxDepth [private], [inherited]
Room's maximum depth.
Definition at line 85 of file Room.hpp.
Referenced by Room::getMaxDepth(), and Room::setMaxDepth().
_maxHeight
float Room::_maxHeight [private], [inherited]
Room's maximum height.
Definition at line 81 of file Room.hpp.
Referenced by Room::getMaxHeight(), and Room::setMaxHeight().
_maxHeightRS
float Room::_maxHeightRS [private], [inherited]
RealSense environment's maximum height.
Definition at line 102 of file Room.hpp.
Referenced by Room::getMaxHeightRS(), and Room::setMaxHeightRS().
_maxWidth
float Room::_maxWidth [private], [inherited]
Room's maximum width.
Definition at line 73 of file Room.hpp.
Referenced by Room::getMaxWidth(), and Room::setMaxWidth().
_maxWidthRS
float Room::_maxWidthRS [private], [inherited]
RealSense environment's maximum width.
Definition at line 94 of file Room.hpp.
Referenced by Room::getMaxWidthRS(), and Room::setMaxWidthRS().
_minHeight
float Room::_minHeight [private], [inherited]
Room's minimum height.
Definition at line 77 of file Room.hpp.
Referenced by Room::getMinHeight(), and Room::setMinHeight().
_minHeightRS
float Room::_minHeightRS [private], [inherited]
RealSense environment's minimum height.
Definition at line 98 of file Room.hpp.
Referenced by Room::getMinHeightRS(), and Room::setMinHeightRS().
_minWidth
float Room::_minWidth [private], [inherited]
Room's minimum width.
Definition at line 69 of file Room.hpp.
Referenced by Room::getMinWidth(), and Room::setMinWidth().
_minWidthRS
float Room::_minWidthRS [private], [inherited]
RealSense environment's minimum width.
Definition at line 90 of file Room.hpp.
Referenced by Room::getMinWidthRS(), and Room::setMinWidthRS().
_xOriginUnity
float Room::_xOriginUnity [private], [inherited]
Digital twin's x axis' origin.
Definition at line 108 of file Room.hpp.
Referenced by Room::getXOriginUnity(), and Room::setXOriginUnity().
_zOriginUnity
float Room::_zOriginUnity [private], [inherited]
Digital twin's z axis' origin.
Definition at line 112 of file Room.hpp.
Referenced by Room::getZOriginUnity(), and Room::setZOriginUnity().
The documentation for this class was generated from the following files:
Room/CVPR_Lab.hpp
Room/CVPR_Lab.cpp